[tool.poetry]
name = "telegramma"
version = "1.0.0"
description = "Modular Telegram bot"
authors = ["Sebastiano Barezzi <barezzisebastiano@gmail.com>"]
license = "GPL-3.0-or-later"
readme = "README.md"
repository = "https://github.com/SebaUbuntu/telegramma"

[tool.poetry.dependencies]
python = "^3.8"
python-telegram-bot = "^20.0a2"
sebaubuntu-libs = "^1.1.1"
twrpdtgen = "^2.4.0"
deepl = "^1.8.0"
speedtest-cli = "^2.1.3"
PyGithub = "^1.55"
requests = "^2.28.0"
GitPython = "^3.1.27"
paramiko = "^2.11.0"
humanize = "^4.1.0"
colour = "^0.1.5"
py-cord = "^2.0.0"
matrix-nio = "^0.19.0"
Pillow = "^9.2.0"
python-magic = "^0.4.27"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
